In [1]:
from datetime import datetime

import pandas as pd

In [2]:
start_date = datetime(2025,1,1)
end_date = datetime(2025,12,31)

date_range = pd.date_range(start_date,end_date)

date_df = pd.DataFrame(date_range,columns=["date"])

In [3]:
date_df.head()

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03
3 2025-01-04
4 2025-01-05

In [4]:
date_df["year"] = date_df["date"].dt.year
date_df["month"] = date_df["date"].dt.month
date_df["day"] = date_df["date"].dt.day
date_df["day_of_week"] = date_df["date"].dt.day_of_week +1
date_df["is_weekend"] = date_df["day_of_week"].isin([6,7])

In [5]:
date_df.sample(10)

          date  year  month  day  day_of_week  is_weekend
8   2025-01-09  2025      1    9            4       False
65  2025-03-07  2025      3    7            5       False
0   2025-01-01  2025      1    1            3       False
331 2025-11-28  2025     11   28            5       False
79  2025-03-21  2025      3   21            5       False
325 2025-11-22  2025     11   22            6        True
355 2025-12-22  2025     12   22            1       False
13  2025-01-14  2025      1   14            2       False
232 2025-08-21  2025      8   21            4       False
89  2025-03-31  2025      3   31            1       False

In [6]:
date_df.to_csv("date_master.csv",index=False)